import type { ItemBaseType } from "../../types";
import { type ItemModifier } from "./modifiers";
import * as modifiers from "./modifiers";

export const corruptionModifiers = {
	weapon: [
		// Low-Rarity (50% chance)
		modifiers.enhancedDamage([40, 80]),
		modifiers.attackRating([150, 250]),
		modifiers.hybridEnhancedDamageToDemonsAttackRatingAgainstDemons([100, 150], 200),
		modifiers.hybridEnhancedDamageToUndeadAttackRatingAgainstUndead([100, 150], 200),
		modifiers.fasterCastRate(10),
		modifiers.lifeOnHit([3, 6]),
		modifiers.lifeAfterEachKill([3, 6]),
		modifiers.manaAfterEachKill([3, 5]),
		modifiers.magicFind([20, 30]),
		modifiers.requirements([25, 50]),
		// Mid-Rarity (30% chance)
		modifiers.fasterCastRate(20),
		modifiers.attackSpeed([30, 40]),
		modifiers.hybridEnhancedDamageLifeStolenPerHit([40, 60], 5),
		modifiers.monsterDefensePerHit([40, 60]),
		modifiers.crushingBlow([20, 30]),
		modifiers.deadlyStrike([20, 30]),
		modifiers.enemyFireResistance([7, 10]),
		modifiers.enemyColdResistance([7, 10]),
		modifiers.enemyLightningResistance([7, 10]),
		modifiers.enemyPoisonResistance([7, 10]),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.hybridAttackSpeedCrushingBlow(30, [20, 30]),
		modifiers.hybridEnhancedDamageAttackSpeed([80, 120], 20),
		modifiers.hybridEnhancedDamageAttackRating([80, 120], 250),
		modifiers.hybridEnhancedDamageDeadlyStrike([50, 70], 25),
		modifiers.hybridEnhancedDamageIgnoreTargetsDefense([60, 80]),
		modifiers.hybridFasterCastRateFireSkillDamage(10, 5),
		modifiers.hybridFasterCastRateColdSkillDamage(10, 5),
		modifiers.hybridFasterCastRateLightningSkillDamage(10, 5),
		modifiers.hybridFasterCastRatePoisonSkillDamage(10, 5),
	],
	shield: [
		// Low-Rarity (48% chance)
		modifiers.fasterHitRecovery([20, 30]),
		modifiers.fasterBlockRate(20),
		modifiers.magicFind([20, 30]),
		modifiers.life([30, 40]),
		modifiers.fireResist([35, 40]),
		modifiers.coldResist([35, 40]),
		modifiers.lightningResist([35, 40]),
		modifiers.poisonResist([35, 40]),
		// Mid-Rarity (32% chance)
		modifiers.hybridIndestructibleEnhancedDefense([50, 80]),
		modifiers.fasterCastRate(10),
		modifiers.hybridFasterBlockRateIncreasedChanceOfBlocking(10, [10, 20]),
		modifiers.maximumLife([4, 6]),
		modifiers.flatPhysicalDamageReduced([6, 10]),
		modifiers.flatMagicDamageReduced([6, 10]),
		modifiers.thornsPerLevel(4), // FIXME: [4, 6]
		modifiers.cannotBeFrozen(),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.curseResistance(10),
		modifiers.allResist([20, 35]),
		modifiers.physicalDamageReduced([6, 8]),
		modifiers.hybridMaxFireResistFireResist([4, 5], [15, 20]),
		modifiers.hybridMaxColdResistColdResist([4, 5], [15, 20]),
		modifiers.hybridMaxLightningResistLightningResist([4, 5], [15, 20]),
		modifiers.hybridMaxPoisonResistPoisonResist([4, 5], [15, 20]),
	],
	quiver: [
		// Low-Rarity (48% chance)
		modifiers.fasterHitRecovery(20),
		modifiers.life([30, 40]),
		modifiers.goldFind([50, 100]),
		modifiers.magicFind([10, 25]),
		modifiers.fireResist([10, 20]),
		modifiers.coldResist([10, 20]),
		modifiers.lightningResist([10, 20]),
		modifiers.poisonResist([10, 20]),
		// Mid-Rarity (32% chance)
		modifiers.fasterRunWalk(10),
		modifiers.chanceToPierce([10, 15]),
		modifiers.enemyFireResistance([5, 10]),
		modifiers.enemyColdResistance([5, 10]),
		modifiers.targetDefense([10, 20]),
		modifiers.attackRating([50, 100]),
		modifiers.manaStolenPerHit([2, 4]),
		modifiers.lifeStolenPerHit([2, 4]),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.attackSpeed(10),
		modifiers.curseResistance(10),
		modifiers.enhancedDamage([30, 40]),
		modifiers.minimumDamage([10, 15]),
		modifiers.maximumDamage([10, 15]),
		modifiers.ignoreTargetDefense(),
		modifiers.allResist([5, 10]),
	],
	helmet: [
		// Low-Rarity (48% chance)
		modifiers.fasterHitRecovery([20, 30]),
		modifiers.enhancedDefense([50, 80]),
		modifiers.magicFind([20, 30]),
		modifiers.replenishLife([20, 30]),
		modifiers.fireResist([30, 35]),
		modifiers.coldResist([30, 35]),
		modifiers.lightningResist([30, 35]),
		modifiers.poisonResist([30, 35]),
		// Mid-Rarity (32% chance)
		modifiers.hybridIndestructibleEnhancedDefense([50, 80]),
		modifiers.hybridAttackRatingLightRadius([150, 250], [2, 4]),
		modifiers.lifeStolenPerHit([3, 5]),
		modifiers.manaStolenPerHit([3, 5]),
		modifiers.maximumLife([4, 6]),
		modifiers.lifeAfterEachKill([3, 4]),
		modifiers.manaAfterEachKill([3, 4]),
		modifiers.cannotBeFrozen(),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.curseResistance(10),
		modifiers.allResist([15, 20]),
		modifiers.physicalDamageReduced([4, 6]),
		modifiers.hybridMaxFireResistFireResist([4, 5], 15),
		modifiers.hybridMaxColdResistColdResist([4, 5], 15),
		modifiers.hybridMaxLightningResistLightningResist([4, 5], 15),
		modifiers.hybridMaxPoisonResistPoisonResist([4, 5], 15),
	],
	chest: [
		// Low-Rarity (48% chance)
		modifiers.fasterHitRecovery([20, 30]),
		modifiers.enhancedDefense([50, 80]),
		modifiers.magicFind([20, 30]),
		modifiers.mana([30, 40]),
		modifiers.fireResist([30, 35]),
		modifiers.coldResist([30, 35]),
		modifiers.lightningResist([30, 35]),
		modifiers.poisonResist([30, 35]),
		// Mid-Rarity (32% chance)
		modifiers.hybridIndestructibleEnhancedDefense([50, 80]),
		modifiers.fasterCastRate(10),
		modifiers.fasterRunWalk(20),
		modifiers.maximumLife([4, 6]),
		modifiers.flatPhysicalDamageReduced([6, 10]),
		modifiers.flatMagicDamageReduced([6, 10]),
		modifiers.thornsPerLevel(4), // FIXME: [4, 6]
		modifiers.cannotBeFrozen(),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.curseResistance(10),
		modifiers.allResist([20, 25]),
		modifiers.physicalDamageReduced([6, 8]),
		modifiers.hybridMaxFireResistFireResist([4, 5], 15),
		modifiers.hybridMaxColdResistColdResist([4, 5], 15),
		modifiers.hybridMaxLightningResistLightningResist([4, 5], 15),
		modifiers.hybridMaxPoisonResistPoisonResist([4, 5], 15),
	],
	gloves: [
		// Low-Rarity (48% chance)
		modifiers.enhancedDefense([50, 80]),
		modifiers.regenerateMana([20, 30]),
		modifiers.goldFind([50, 100]),
		modifiers.magicFind([10, 25]),
		modifiers.fireResist([10, 15]),
		modifiers.coldResist([10, 15]),
		modifiers.lightningResist([10, 15]),
		modifiers.poisonResist([10, 15]),
		// Mid-Rarity (32% chance)
		modifiers.chanceToPierce([10, 15]),
		modifiers.fasterBlockRate([10, 20]),
		modifiers.attackRating([100, 150]),
		modifiers.lifeStolenPerHit([2, 3]),
		modifiers.manaStolenPerHit([2, 3]),
		modifiers.allAttributes([3, 6]),
		modifiers.life([20, 40]),
		modifiers.replenishLife([15, 20]),
		// High-Rarity (20% chance)
		modifiers.fasterCastRate(10),
		modifiers.attackSpeed(10),
		modifiers.increasedChanceOfBlocking(10),
		modifiers.enhancedDamage([30, 40]),
		modifiers.targetDefense([15, 25]),
		modifiers.deadlyStrike(10),
		modifiers.manaAfterEachKill([3, 4]),
		modifiers.allResist([5, 8]),
	],
	boots: [
		// Low-Rarity (48% chance)
		modifiers.enhancedDefense([50, 80]),
		modifiers.regenerateMana([10, 15]),
		modifiers.goldFind([50, 100]),
		modifiers.magicFind([10, 25]),
		modifiers.fireResist([15, 20]),
		modifiers.coldResist([15, 20]),
		modifiers.lightningResist([15, 20]),
		modifiers.poisonResist([15, 20]),
		// Mid-Rarity (32% chance)
		modifiers.hybridIndestructibleEnhancedDefense([50, 80]),
		modifiers.fasterBlockRate(10),
		modifiers.fasterHitRecovery(10),
		modifiers.life([20, 40]),
		modifiers.allResist([5, 8]),
		modifiers.lifeAfterEachKill([2, 3]),
		modifiers.manaAfterEachKill([2, 3]),
		modifiers.replenishLife([15, 25]),
		// High-Rarity (20% chance)
		modifiers.fasterRunWalk(15),
		modifiers.reducedCurseDuration(20),
		modifiers.physicalDamageReduced([3, 4]),
		modifiers.increasedChanceOfBlocking(10),
		modifiers.hybridMaxFireResistFireResist([2, 3], 10),
		modifiers.hybridMaxColdResistColdResist([2, 3], 10),
		modifiers.hybridMaxLightningResistLightningResist([2, 3], 10),
		modifiers.hybridMaxPoisonResistPoisonResist([2, 3], 10),
	],
	amulet: [
		// Low-Rarity (48% chance)
		modifiers.strength([6, 12]),
		modifiers.dexterity([6, 12]),
		modifiers.vitality([6, 12]),
		modifiers.energy([6, 12]),
		modifiers.fireResist([15, 20]),
		modifiers.coldResist([15, 20]),
		modifiers.lightningResist([15, 20]),
		modifiers.poisonResist([15, 20]),
		// Mid-Rarity (32% chance)
		modifiers.chanceToPierce([10, 20]),
		modifiers.fasterHitRecovery(10),
		modifiers.increasedChanceOfBlocking(10),
		modifiers.lifeAfterEachKill([2, 3]),
		modifiers.manaAfterEachKill([2, 3]),
		modifiers.allAttributes([6, 8]),
		modifiers.goldFind([60, 100]),
		modifiers.magicFind([20, 30]),
		// High-Rarity (20% chance)
		modifiers.allSkills(1),
		modifiers.fasterCastRate(10),
		modifiers.fasterRunWalk(10),
		modifiers.curseResistance(10),
		modifiers.enhancedDamage([30, 40]),
		modifiers.cannotBeFrozen(),
		modifiers.maxAllResist(2),
		modifiers.allResist([7, 10]),
	],
	ring: [
		// Low-Rarity (48% chance)
		modifiers.strength([7, 10]),
		modifiers.dexterity([7, 10]),
		modifiers.vitality([7, 10]),
		modifiers.energy([7, 10]),
		modifiers.fireResist([10, 15]),
		modifiers.coldResist([10, 15]),
		modifiers.lightningResist([10, 15]),
		modifiers.poisonResist([10, 15]),
		// Mid-Rarity (32% chance)
		modifiers.attackRating([100, 150]),
		modifiers.lifeAfterEachKill([2, 3]),
		modifiers.manaAfterEachKill([2, 3]),
		modifiers.flatPhysicalDamageReduced([4, 6]),
		modifiers.flatMagicDamageReduced([4, 6]),
		modifiers.life([30, 40]),
		modifiers.goldFind([40, 80]),
		modifiers.magicFind([15, 20]),
		// High-Rarity (20% chance)
		modifiers.fasterCastRate(10),
		modifiers.fasterRunWalk(10),
		modifiers.reducedCurseDuration(10),
		modifiers.manaStolenPerHit([3, 4]),
		modifiers.lifeStolenPerHit([3, 4]),
		modifiers.allAttributes([4, 6]),
		modifiers.allResist([4, 6]),
		modifiers.physicalDamageReduced(3),
	],
	belt: [
		// Low-Rarity (48% chance)
		modifiers.strength([7, 10]),
		modifiers.dexterity([7, 10]),
		modifiers.vitality([7, 10]),
		modifiers.energy([7, 10]),
		modifiers.fireResist([10, 15]),
		modifiers.coldResist([10, 15]),
		modifiers.lightningResist([10, 15]),
		modifiers.poisonResist([10, 15]),
		// Mid-Rarity (32% chance)
		modifiers.chanceToPierce([10, 15]),
		modifiers.fasterHitRecovery(10),
		modifiers.allAttributes([3, 6]),
		modifiers.replenishLife([15, 20]),
		modifiers.attackRating([100, 150]),
		modifiers.thornsPerLevel(2), // FIXME: [2, 4]
		modifiers.goldFind([60, 100]),
		modifiers.magicFind([20, 30]),
		// High-Rarity (20% chance)
		modifiers.fasterCastRate(10),
		modifiers.attackSpeed(10),
		modifiers.fasterRunWalk(10),
		modifiers.reducedCurseDuration(20),
		modifiers.increasedChanceOfBlocking(10),
		modifiers.maxAllResist(2),
		modifiers.allResist([5, 8]),
		modifiers.physicalDamageReduced([3, 4]),
	],
	// annihilus
	charm: [
		modifiers.allSkills(1),
		modifiers.hybridVitalityEnergy([20, 25], [10, 15]),
		modifiers.allResist([5, 10]),
		modifiers.experienceGained([3, 5]),
	],
} as const satisfies Record<ItemBaseType, ItemModifier[]>;
